application:
  port: 8000
  host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
email_client:
  base_url: http://127.0.0.1 
  sender_email: "test@test.test"
