application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "test@test.test"
  api_token: "api-secret-token"
  timeout_ms: 10000
